---
title: "Práctica 2. Tidymodels"
author: "Alejandro Noel Hernández  Gutiérrez"
date: "2023_01_31"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
vignette: >
  %\VignetteIndexEntry{Práctica 2. Tidymodels}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  markdown: 
    wrap: 72
---

```{r}
# Tablas sencillas
library(tidyverse)
library(kableExtra)
# Tablas páginadas customizadas
library(DT)
# Funcion para obtener datatable (datos, indice tabla, nombre)
custom_dt <- function(data, indice, nombre) {
  table_n <- paste("Table ", indice) 
  dt <- datatable(data,
                  caption = htmltools::tags$caption(
                  style = 'caption-side: bottom; text-align: center;',
                  table_n, htmltools::em(nombre)),
                  extensions = 'FixedColumns',
                  rownames= FALSE,
                  filter = 'top',
                  options = list(
                  pageLength = 5,
                  autoWidth = TRUE,
                  columnDefs = 
                  list(list(width = '300px', targets = c(0,7))),
                  scrollX = TRUE,
                  escape = T)
                  )
  return(dt)
}

```

```{r}
# Tablas sencillas
library(tidyverse)
library(kableExtra)
# Tablas páginadas customizadas
library(DT)
# Funcion para obtener datatable (datos, indice tabla, nombre)
custom_dt <- function(data, indice, nombre) {
  table_n <- paste("Table ", indice) 
  dt <- datatable(data,
                  caption = htmltools::tags$caption(
                  style = 'caption-side: bottom; text-align: center;',
                  table_n, htmltools::em(nombre)),
                  extensions = 'FixedColumns',
                  rownames= FALSE,
                  filter = 'top',
                  options = list(
                  pageLength = 5,
                  autoWidth = TRUE,
                  columnDefs = 
                  list(list(width = '300px', targets = c(0,7))),
                  scrollX = TRUE,
                  escape = T)
                  )
  return(dt)
}

```

# Obtención y exploración de datos.

```{r}
library(modeldata)
data <- ames

custom_dt(data, 1, "Ames dataset.")
```

```{r}
summarise(data)
```
