---
title: "Workflows tidymodels"
author: "Alejandro Noel Hernández Gutiérrez"
date: "2023-01-31"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r}
# Librerías
library(doParallel)
library(tictoc)
library(beepr)
library(tidyverse)
library(tidymodels)

```

```{r}
data("SaratogaHouses", package = "mosaicData")
df <- SaratogaHouses
```

# Definición del modelo

```{r}
# Cargar los datos
#install.packages("mosaicData")
data("SaratogaHouses", package = "mosaicData")
df <- SaratogaHouses
# Split de los datos
set.seed(123)
split_inicial <- initial_split(data = df, # Datos
                               prop = 0.8, # Proporción del train
                               strata =  price # variable de salida/ busca que entre test y train tenga distribución similar de price
)
data_train <- training(split_inicial)
data_test <- testing(split_inicial)
# Definición del modelo
model_tree <- decision_tree(
  mode = "regression",
  tree_depth = tune(),
  min_n = tune()) %>% 
  set_engine(engine = "rpart")

# Definición del preprocesado

```

# Definición del preprocesado

```{r}
transformer <- recipe(formula = price ~ .,
                      data = data_train) %>% 
  step_naomit(all_predictors()) %>% 
  step_nzv(all_predictors()) %>% 
  step_center(all_numeric(), -all_outcomes()) %>% 
  step_scale(all_numeric(), -all_outcomes()) %>% 
  step_dummy(all_nominal(), -all_outcomes())

transformer
```

# Definición de la validación

```{r}
set.seed(1234)
vc_folds <- vfold_cv(data = data_train,
                      v = 5,
                      strata = price)
vc_folds
```

# Definir workflow

```{r}
workflow_model <- workflow() %>% add_recipe(transformer) %>% add_model(model_tree)
workflow_model
```

# Definición de estrategia de tunning

## Definición del grid

```{r}
grid_hiperparametros <- grid_regular(
  tree_depth(range = c(1,10), trans = NULL), # 10 es la máxima profundidad. (Rangos de busqueda)
  min_n(range = c(2,50), trans = NULL), # 50 Max. leaves
  levels = c(3,3) # Número de hiperparámetros
  
)

grid_hiperparametros
```

# Fit con todo lo anterior

```{r}
registerDoParallel(cores = detectCores()-1)
# tune_grid() cambia cuando es bayesiano
# workflow ya trae receta y modelo
# Definir validación cruzada
tic()
fit_tune <- tune_grid(
  object = workflow_model,
  resamples = vc_folds,
  metrics = metric_set(rmse),
  control = control_resamples(save_pred = TRUE),
  grid = grid_hiperparametros
)
toc()
beep(1)
stopImplicitCluster()

```

# Tarea. Seleccionar el mejor modelo

```{r}
best <- select_best(fit_tune, metric = "rmse")
best
```

# Modelo Final

```{r}
final_model <- finalize_workflow(x = workflow_model, parameters = best) %>% 
  fit(data = data_train) %>% extract_fit_parsnip()

```

# Evaluación
